### ISSUE TITLE
How can I make TSE launch this mod automatically?

### ISSUE THREAD

**Issue by daemonspudguy** [SamClassicPatch/Mod#2]

**Comment by DreamyCecil** [comment]
It already runs automatically by default in v1.07 for the game and any mod that doesn't have its own DLL files.

**Comment by daemonspudguy** [comment]
It doesn't appear to for me, because the menu doesn't match the HUD theme.

**Comment by DreamyCecil** [comment]
If any other feature of the mod works (that you can set under mod settings), then it does. There might be a loading problem with theme configs.

**Comment by daemonspudguy** [comment]
Not that I can tell.

**Comment by daemonspudguy** [comment]
The theme configs do load if I go into the mods menu and launch the classics patch mod there.

**Comment by daemonspudguy** [comment]
Nevermind, it suddenly started working.
