### ISSUE TITLE
Loading screen shows Second Encounter map when playing First Encounter levels

### ISSUE THREAD

**Issue by daemonspudguy** [SamClassicPatch/Mod#3]
It isn't game breaking at all, but it is weird and I'm wondering if it's fixable.

**Comment by DreamyCecil** [comment]
There's no solution for 1.6.2 but it has been fixed for the upcoming update: https://github.com/SamClassicPatch/Mod/commit/bd5e343cb5acc68d971c3d2f1d677199f3efc069
